# Generated by Django 4.2 on 2023-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Rating star', 'verbose_name_plural': 'Rating stars'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP-Address'),
        ),
    ]
